name: Lint and Build Checks

on:
    push:
        branches:
            - master
    
    pull_request:
        branches:
            - master

defaults:
    run:
        shell: bash    

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            
            - name: Set Up Nodejs
              uses: actions/setup-node@v2
              with:
                node-version: 18
                cache: "npm"
            
            - name: Install Dependencies
              run: npm install
            
            - name: Build Check
              run: npm run build

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            
            - name: Set Up Nodejs
              uses: actions/setup-node@v2
              with:
                node-version: 18
                cache: "npm"
            
            - name: Install Dependencies
              run: npm install
            
            - name: Build Check
              run: npm run lint